### ISSUE TITLE
Feature-Request: Calculate how much of Bitcoins past history is already compensating

### ISSUE THREAD

**Issue by rootzoll** [netpositive-money/netpositive-money.github.io#9]
Once we have statistics on donations see #7 .. it would be great to calculate and visualize how much of Bitcoins history (started from the beginning) has been offsett. That would be a great statistic to share and to celebrate.

**Comment by stefanwouldgo** [comment]
This is already implemented on the calculator page. It just doesn't make much sense at the moment because the data we have only starts in 2015, and so we have only offset until the first day or so.

**Comment by rootzoll** [comment]
Maybe assuming a linear growth from start to 2015 is kind of a "worst case upper limit" we could work with?

**Comment by stefanwouldgo** [comment]
Yeah, we might pad the data somehow. I had someone who promised me to give us better data from 2009 on, but they haven't come through so far. I will ask them again right now.
